### ISSUE TITLE
🔥  "Internal Server Error" on when signing up with Google

### ISSUE THREAD

**Issue by thaikolja** [Upstatement/dev-env-setup#13]
Hi,

While I wanted to test this repository on Project Computer, the signing up process failed. I entered my Google account, and then it led me to [`/failture#`](https://computer.upstatement.com/failure#) with the message `Internal Server Error`, rendering the entire project useless.

Upon going to the previous page, the login screen, a different error site came up, which, according to the description, was intentional:

![Screenshot](https://user-images.githubusercontent.com/37884870/114574150-49ea4d80-9c79-11eb-9ea1-5aa8e0b39e8c.png)

I thought you might want to know. I don't know if this happens to other users too, but I assume it does since the last commit to the repository was [14 months respectively 2 years ago](https://github.com/Upstatement/dev-env-setup/graphs/commit-activity).

**Comment by bchiang7** [comment]
Hi @thaikolja, sorry it's not more clearly stated, but this repository is only meant for Upstatement employees (who already have existing `@upstatement.com` emails) to get their dev environments set up.

**Comment by thaikolja** [comment]
I see, sorry then. Maybe you should make it private then?

**Comment by bchiang7** [comment]
We have it public so that new employees who haven't been added to our GitHub organization yet can still get started setting up their computers. Sorry for the confusion!
